# TCL Synthesis Script for DispMapIntegSum2LCacc
# Auto-generated by HLSFactory
# PARADE ARA Simulator - LCAcc Accelerator

# Set project name
set project_name "DispMapIntegSum2LCacc_prj"
set solution_name "solution1"

# Open/Create project
open_project -reset $project_name

# Add source files
add_files DispMapIntegSum2LCacc.h
add_files -tb testbench.cpp

# Set top-level function (heuristic)
set top_function "DispMapIntegSum2LCacc_sig"

# Open solution
open_solution -reset $solution_name

# Set target device (Xilinx FPGA)
set_part {xc7z020clg484-1}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Configure synthesis
csynth_design

# Export design (optional)
# export_design -rtl verilog -format ip_catalog

# Close solution and project
close_solution
close_project

puts "Synthesis complete for DispMapIntegSum2LCacc"
exit
