# TCL Synthesis Script for reg_hbm-bandwidth
# Auto-generated by HLSFactory

# Open/create project
open_project reg_hbm-bandwidth
set_top Copy

# Add source files
add_files bandwidth.cpp
add_files bandwidth.h
add_files -tb bandwidth-host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 10ns period
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
