# TCL Synthesis Script for reg_lu_decompose_hls
# Auto-generated by HLSFactory

# Open/create project
open_project reg_lu_decompose_hls
set_top init_array

# Add source files
add_files kernel.c
add_files kernel.h
add_files kernel_kernel.h
add_files -tb kernel_host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 10ns period
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
