# TCL Synthesis Script for reg_cnn_vitis_hls
# Auto-generated by HLSFactory

# Open/create project
open_project reg_cnn_vitis_hls
set_top main

# Add source files
add_files kernel.c
add_files kernel.h
add_files kernel_host.hpp
add_files kernel_kernel.h
add_files -tb kernel_host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 5ns period
create_clock -period 5 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
