# TCL Synthesis Script for TDLCA_EKF_SLAM
# Generated by HLSFactory

open_project -reset TDLCA_EKF_SLAM_proj

# Add source files
add_files TDLCA_EKF_SLAM.cpp
add_files -tb JacobiansLCacc.h
add_files -tb SphericalCoordsLCacc.h

# Set top function
set_top EKF_SLAMLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
