/*
 * Testbench for orc_proc
 * Auto-generated by HLSFactory
 */

#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <iostream>
#include <vector>
#include <chrono>

// Include design headers
#include "../src/stubs/ap_int.h"
#include "../src/stubs/tapa.h"

// Design typedefs from orc_proc.h
#define AP_INT_MAX_W 4096
#define DMUL 16
#define DECOMP_DEPTH 4072

typedef ap_uint<512> _512b;
typedef ap_int<512> _512bi;
typedef ap_uint<2048> _2048b;
typedef ap_uint<1024> _1024b;
typedef ap_uint<256> _256b;
typedef ap_uint<128> _128b;
typedef ap_uint<72> _72b;
typedef ap_uint<320> _320b;

// Top function declaration
void orc_proc(
    tapa::mmap<_512b> input_port,
    tapa::mmap<_512b> FilterConf_port,
    tapa::mmap<_512b> output_port0_32b_8b,
    tapa::mmap<_512b> output_port1_16b_8b,
    tapa::mmap<_512b> output_port2_16b_8b,
    tapa::mmap<_512b> output_port3_8b,
    tapa::mmap<_512b> data_Idx,
    tapa::mmap<_512b> output_port4_Track,
    uint32_t data_count
);

// Test data generation
void generate_test_data(_512b* input_data, _512b* config_data, uint32_t count) {
    // Initialize input data with test pattern
    for (uint32_t i = 0; i < count; i++) {
        input_data[i] = i * 0x0101010101010101ULL;
    }
    
    // Setup filter configuration
    // Config word 0: Filter parameters
    config_data[0] = 0;  // idx_flag=0, range_flag=0, RROP=0, LROP=0, RR=0, LR=0
    // Config word 1: Read count
    config_data[1] = count;
    config_data[2] = 0;  // Will hold filtered row count after execution
}

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "Testbench for orc_proc" << std::endl;
    std::cout << "========================================" << std::endl;
    
    const uint32_t DATA_COUNT = 64;  // Number of 512-bit words
    
    // Allocate test buffers
    std::vector<_512b, tapa::aligned_allocator<_512b>> input_data(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> config_data(3);
    std::vector<_512b, tapa::aligned_allocator<_512b>> output0(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> output1(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> output2(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> output3(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> idx_data(DATA_COUNT);
    std::vector<_512b, tapa::aligned_allocator<_512b>> track_data(DATA_COUNT);
    
    // Initialize data
    generate_test_data(input_data.data(), config_data.data(), DATA_COUNT);
    
    // Create mmap wrappers
    tapa::mmap<_512b> input_port(input_data.data());
    tapa::mmap<_512b> config_port(config_data.data());
    tapa::mmap<_512b> output0_port(output0.data());
    tapa::mmap<_512b> output1_port(output1.data());
    tapa::mmap<_512b> output2_port(output2.data());
    tapa::mmap<_512b> output3_port(output3.data());
    tapa::mmap<_512b> idx_port(idx_data.data());
    tapa::mmap<_512b> track_port(track_data.data());
    
    std::cout << "Running orc_proc..." << std::endl;
    
    auto start = std::chrono::high_resolution_clock::now();
    
    // Call top function
    orc_proc(
        input_port,
        config_port,
        output0_port,
        output1_port,
        output2_port,
        output3_port,
        idx_port,
        track_port,
        DATA_COUNT
    );
    
    auto end = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
    
    std::cout << "Execution time: " << duration.count() << " microseconds" << std::endl;
    std::cout << "Test completed successfully!" << std::endl;
    
    return 0;
}
