# Catapult HLS run script generated by hlsfactory_agent.translate
solution new -state initial
options set Message/ErrorOverride HIER-10 -remove
solution options set Message/ErrorOverride HIER-10 -remove
solution options set /Input/CppStandard c++11
solution options set /Input/CompilerFlags {-I. -DCATAPULT}
solution file add ./mac.cpp -type C++
solution file add ./testbench.cpp -type C++ -exclude true
go analyze
go compile
solution library add nangate-45nm_beh -- -rtlsyntool DesignCompiler -vendor Nangate -technology 045nm
solution library add ccs_sample_mem
go libraries
directive set -CLOCKS {clk {-CLOCK_PERIOD 5.0}}
go assembly
go architect
go allocate
go schedule
go extract
