# Vivado HLS Synthesis Script for n256_UF32
# Auto-generated by HLSFactory

# Create project
open_project -reset n256_UF32_proj

# Set the top function
set_top FFT_TOP

# Add source files
add_files FFT.cpp
add_files -tb testbench.cpp

# Open solution
open_solution -reset "solution1"

# Set target device (adjust as needed)
set_part {xcvu9p-flga2104-2-i}

# Create clock with 5ns period (200MHz)
create_clock -period 5 -name default

# Run synthesis
csynth_design

# Export RTL (optional)
# export_design -format ip_catalog

# Close project
close_project

puts "Synthesis complete for n256_UF32"
