# TCL Synthesis Script for TDLCA_Deblur_Modified
# Generated by HLSFactory

open_project -reset TDLCA_Deblur_Modified_proj

# Add source files
add_files TDLCA_Deblur.cpp
add_files -tb Blur1LCacc.h
add_files -tb Blur2LCacc.h
add_files -tb Blur3LCacc.h
add_files -tb Deblur1LCacc.h
add_files -tb Deblur2LCacc.h
add_files -tb Denoise1LCacc.h

# Set top function
set_top Deblur_ModifiedLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
