# TCL Synthesis Script for TDLCA_Disparity_Map
# Generated by HLSFactory

open_project -reset TDLCA_Disparity_Map_proj

# Add source files
add_files TDLCA_Disparity_Map.cpp
add_files -tb DispMapCompSADLCacc.h
add_files -tb DispMapFindDispLCacc.h
add_files -tb DispMapIntegSum1LCacc.h
add_files -tb DispMapIntegSum2LCacc.h

# Set top function
set_top Disparity_MapLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
