# HLS Synthesis Script for P2MC_cdc_cg
# Auto-generated by HLSFactory

# Create project
open_project P2MC_cdc_cg

# Add source files
add_files top.cpp -cflags "-I/workspace/stubs"
add_files -tb testbench.cpp -cflags "-I/workspace/stubs"

# Set top function
set_top kernel_sep

# Create solution
open_solution "solution1"

# Set target part
set_part {xcvu9p-flga2104-2-i}

# Create clock (10ns = 100MHz)
create_clock -period 10 -name default

# Run synthesis
csynth_design

# Run co-simulation (optional)
# cosim_design

# Export RTL (optional)
# export_design -format ip_catalog

# Exit
exit
