# TCL Synthesis Script for reg_knn
# Auto-generated by HLSFactory

# Open/create project
open_project reg_knn
set_top load

# Add source files
add_files knn.cpp
add_files knn.h
add_files -tb knn-host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 5ns period
create_clock -period 5 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
