# TCL Synthesis Script for TDLCA_LPCIP_Desc
# Generated by HLSFactory

open_project -reset TDLCA_LPCIP_Desc_proj

# Add source files
add_files TDLCA_LPCIP_Desc.cpp
add_files -tb LPCIPLCacc.h

# Set top function
set_top LPCIP_DescLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
