# TCL Synthesis Script for TDLCA_StreamCluster
# Generated by HLSFactory

open_project -reset TDLCA_StreamCluster_proj

# Add source files
add_files TDLCA_StreamCluster.cpp
add_files -tb StreamCluster1LCacc.h
add_files -tb StreamCluster3LCacc.h
add_files -tb StreamCluster4LCacc.h
add_files -tb StreamCluster5LCacc.h
add_files -tb StreamCluster6LCacc.h

# Set top function
set_top StreamClusterLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
