# Vivado HLS TCL Script for loopback_nlb
# Auto-generated by HLSFactory

set design_name "loopback_nlb"
set top_func "compute"

# Create project
open_project -reset $design_name

# Add source files
add_files "NLBApp.h"
add_files "NLB.cpp"
add_files -tb "testbench.cpp"

# Set top function
set_top $top_func

# Create solution
open_solution -reset "solution1"

# Set device (default to Xilinx xc7z020)
set_part {xc7z020clg484-1}

# Create clock
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Export design
export_design -format ip_catalog

# Close project
close_project

puts "HLS synthesis completed for $design_name"
