# Vitis HLS Synthesis Script for k_compress_store
# Auto-generated by HLSFactory

open_project k_compress_store_proj
set_top k_compress_store

# Add source files
add_files k_compress_store.cpp

# Add testbench
add_files -tb tb_k_compress_store.cpp

# Open solution
open_solution -reset "solution1"

# Set target device (Alveo U280)
set_part {xcu280-fsvh2892-2L-e}

# Create clock (300MHz default)
create_clock -period 3.33 -name default

# Run C synthesis
csynth_design

# Export design (optional)
# export_design -rtl verilog -format ip_catalog

exit
