from __future__ import annotations

from pathlib import Path

from hlsfactory_agent.spec import PragmaRule, TargetSpec
from hlsfactory_agent.targets.catapult import CATAPULT

DIR_PKG = Path(__file__).resolve().parent.parent
DIR_AC_TYPES_INCLUDE = DIR_PKG / "ac_types_include"
DIR_XLS_EMU_INCLUDE = DIR_PKG / "xls_emu_include"


XLSCC = TargetSpec(
    name="xlscc",
    display_name="Google XLS (xlscc)",
    include_dir=DIR_AC_TYPES_INCLUDE,
    include_dir_name="ac_types_include",
    extra_include_dirs=((DIR_XLS_EMU_INCLUDE, "xls_emu_include"),),
    cxx_std_check="c++17",
    header_map={
        "ap_int.h": "ac_int.h",
        "ap_fixed.h": "ac_fixed.h",
        "hls_stream.h": "xls_emu.h  (host emulation of __xls_channel; empty under xlscc, which provides the type itself)",
    },
    type_map={
        "ap_int<N>": "ac_int<N, true>",
        "ap_uint<N>": "ac_int<N, false>",
        "ap_fixed<W, I>": "ac_fixed<W, I, true>",
        "ap_ufixed<W, I>": "ac_fixed<W, I, false>",
        "hls::stream<T>": "__xls_channel<T>",
        "stream.read()": "channel.read()",
        "stream.write(v)": "channel.write(v)",
        "float / double": "NOT SUPPORTED by XLS; if the design needs floating point, stop and report it as untranslatable",
    },
    pragma_rules=(
        PragmaRule(
            source="#pragma HLS PIPELINE II=n  (inside the loop body)",
            target="#pragma hls_pipeline_init_interval n",
            placement="on the line directly BEFORE the `for` statement",
            note="xlscc honors II=1 reliably; larger values may be ignored, record it in the report",
        ),
        PragmaRule(
            source="#pragma HLS UNROLL  (inside the loop body)",
            target="#pragma hls_unroll yes",
            placement="on the line directly BEFORE the `for` statement",
        ),
        PragmaRule(
            source="#pragma HLS UNROLL factor=n",
            target="#pragma hls_unroll yes",
            placement="on the line directly BEFORE the `for` statement",
            note="xlscc has no partial unroll; record the factor as lost",
            category="lossy",
        ),
        PragmaRule(
            source="#pragma HLS ARRAY_PARTITION ...",
            target=None,
            placement="removed from source",
            note="XLS has no partition; arrays become registers or memories by its own rules. List as DROPPED.",
            category="absent",
        ),
        PragmaRule(
            source="#pragma HLS DATAFLOW",
            target=None,
            placement="removed from source",
            note="XLS procs are a different model; record as DROPPED.",
            category="absent",
        ),
        PragmaRule(
            source="any other #pragma HLS ...",
            target=None,
            placement="removed from source",
            note="Remove and list as DROPPED with the original text.",
            category="absent",
        ),
    ),
    forbidden_patterns=CATAPULT.forbidden_patterns,
    required_files=("testbench.cpp", "run_xlscc.sh", "translation_report.md"),
    driver_file="run_xlscc.sh",
    driver_required_tokens=("xlscc", "opt_main", "codegen_main"),
    top_marker="#pragma hls_top",
    blocking_types=("float", "double"),
    extra_rules=(
        "Loops that are not pipelined must be fully unrolled for xlscc: add `#pragma hls_unroll yes` before any loop with no pragma and a constant bound; if the bound is not constant, report it.",
        "No dynamic memory, no recursion, no pointers into arrays; rewrite with indexing.",
        "The testbench is host-only: it includes `xls_emu.h` for the channel type and is never given to xlscc.",
        "ac_int and ac_fixed require an explicit signedness template parameter; ap_int is signed, ap_uint is unsigned.",
    ),
)


def render_xlscc_driver(top: str, sources: list[str]) -> str:
    kernel = " ".join(sources)
    return (
        "#!/bin/sh\n"
        "# XLS run script generated by hlsfactory_agent.translate\n"
        "# Requires the XLS binaries on PATH and -I paths for ac types; xls_emu.h is empty under xlscc.\n"
        "set -e\n"
        f"xlscc {kernel} --top {top} > {top}.ir\n"
        f"opt_main {top}.ir > {top}.opt.ir\n"
        f"codegen_main --generator=pipeline --delay_model=unit --pipeline_stages=1 {top}.opt.ir > {top}.v\n"
    )
