# Vitis HLS Synthesis Script for self-attn_sequential
# Generated by HLSFactory

open_project self-attn_sequential
set_top measure_cycle

# Add source files
add_files kernel.cpp

# Add testbench files

# Create solution
open_solution "solution1"
set_part {xcvu9p-flga2104-2-e}
create_clock -period 5 -name default

# Run synthesis
csynth_design

# Export design (optional)
# export_design -format ip_catalog -description "self-attn_sequential HLS Design"

exit
