# TCL Synthesis Script for spmm/sextans-u280-split-bram-uram
# Generated by HLSFactory Pipeline
# Date: 2026-02-24 03:31:07

set design_name "spmm/sextans-u280-split-bram-uram"
set src_dir "."

# Create project
open_project -reset $design_name

# Add source files
add_files $src_dir/sextans.cpp

# Set top function
set_top spmm_sextans_u280_split_bram_uram

# Add testbench files

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx U280 as default)
set_part {{xcu280-fsvh2892-2L-e}}

# Create clock with 300MHz
create_clock -period 3.33

# Run synthesis
csynth_design

# Export design
export_design -rtl verilog -format ip_catalog

exit
