# TCL Synthesis Script for reg_page_rank_tapa
# Auto-generated by HLSFactory

# Open/create project
open_project reg_page_rank_tapa
set_top Control

# Add source files
add_files page-rank.cpp
add_files nxgraph.hpp
add_files page-rank-kernel.h
add_files page-rank.h
add_files -tb page-rank-host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 10ns period
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
