# TCL Synthesis Script for apps_cannon
# Auto-generated by HLSFactory

# Open/create project
open_project apps_cannon
set_top Scatter

# Add source files
add_files cannon.cpp
add_files -tb cannon-host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 10ns period
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
