# TCL Script for NiN HLS Synthesis
# Generated by HLSFactory

open_project NiN
set_top network
add_files src.cpp
add_files -tb tb.cpp
add_files -cflags "-I./includes"
add_files -tb -cflags "-I./includes"
open_solution "solution1"
set_part {xcvu9p-flga2104-2-i}
create_clock -period 10 -name default
config_compile -pipeline_loops 1
config_export -format ip_catalog -rtl vhdl
csynth_design
export_design -format ip_catalog -description "NiN Spiking CNN" -vendor "SFU-HiAccel" -version "1.0"
close_project
