# TCL Synthesis Script for TDLCA_Robot_Localization
# Generated by HLSFactory

open_project -reset TDLCA_Robot_Localization_proj

# Add source files
add_files TDLCA_Robot_Localization.cpp
add_files -tb RobLocLCacc.h

# Set top function
set_top Robot_LocalizationLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
