# TCL Synthesis Script for reg_spmv-hisparse-mmap_hls
# Auto-generated by HLSFactory

# Open/create project
open_project reg_spmv-hisparse-mmap_hls
set_top CPSR_matrix_loader

# Add source files
add_files spmv.cpp
add_files data_formatter.h
add_files data_loader.h
add_files -tb host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 3.3ns period
create_clock -period 3.3 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
