# Vitis HLS Synthesis Script for mlp_spatial
# Generated by HLSFactory

open_project mlp_spatial
set_top measure_cycle

# Add source files
add_files kernel.cpp

# Add testbench files

# Create solution
open_solution "solution1"
set_part {xcvu9p-flga2104-2-e}
create_clock -period 5 -name default

# Run synthesis
csynth_design

# Export design (optional)
# export_design -format ip_catalog -description "mlp_spatial HLS Design"

exit
