# TCL Synthesis Script for reg_spmm_sextans-u280-split-bram-uram_tapa
# Auto-generated by HLSFactory

# Open/create project
open_project reg_spmm_sextans-u280-split-bram-uram_tapa
set_top async_read

# Add source files
add_files sextans.cpp
add_files mmio.h
add_files modules.h
add_files sextans.h
add_files sparse_helper.h
add_files -tb sextans-host.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 3.3ns period
create_clock -period 3.3 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
