# TCL Synthesis Script for ORC Decomp Design
# Generated by HLSFactory

open_project orc_decomp
set_top DecompHead

# Add source files
add_files orcDecomp.h
add_files orc_proc.h

# Add testbench
add_files -tb tb_orcDecomp.cpp

# Open solution
open_solution "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create default clock (250MHz = 4ns)
create_clock -period 4 -name default

# Configuration
config_compile -ignore_long_run_time
config_export -format ip_catalog -rtl verilog

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run co-simulation
cosim_design

# Export design
export_design -format ip_catalog -description "ORC Decompression Module" -vendor "SFU-HiAccel" -version "1.0"

exit
