# TCL Synthesis Script for TDLCA_MatMul
# Generated by HLSFactory

open_project -reset TDLCA_MatMul_proj

# Add source files
add_files TDLCA_MatMul.cpp
add_files -tb MatMulLCacc.h

# Set top function
set_top MatMulLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
