# Vitis HLS Synthesis Script for tapa_qcf
# Auto-generated by HLSFactory

open_project tapa_qcf_proj
set_top tapa_qcf

# Add source files
add_files tapa_qcf.cpp

# Add testbench
add_files -tb tb_tapa_qcf.cpp

# Open solution
open_solution -reset "solution1"

# Set target device (Alveo U280)
set_part {xcu280-fsvh2892-2L-e}

# Create clock (300MHz default)
create_clock -period 3.33 -name default

# Run C synthesis
csynth_design

# Export design (optional)
# export_design -rtl verilog -format ip_catalog

exit
