# run cosim or generate bitstream
TARGET=hw
# TARGET=hw_emu     ## (NOTE: As of May 2, this is untested)
# DEBUG=-g

KERNEL_NAME="Knn"
TOP="knn"
XO="$(pwd)/${TOP}.xo"
CONSTRAINT="$(pwd)/${TOP}_floorplan.tcl"
#CONFIG_FILE="../src/knn.ini"
CONFIG_FILE="$(pwd)/run/link_config.ini"  ### This only works if we are using the U280, because the INI file is generated by autobridge for the auto-HBM setup.
TARGET_FREQUENCY=225
MAX_SYNTH_JOBS=16

## in our experience, the EarlyBlockPlacement strategy works better
## for designs with lots of DSPs and BRAMs
#STRATEGY="Explore"
#PLACEMENT_STRATEGY="EarlyBlockPlacement"

PLATFORM=xilinx_u280_xdma_201920_3

# where to save the intermediate results
OUTPUT_DIR="$(pwd)/vitis_run_${TARGET}"

# check that the floorplan tcl exists
if [ ! -f "$CONSTRAINT" ]; then
    echo "no constraint file found"
    exit
fi

v++ ${DEBUG}\
  --link \
  --output "${OUTPUT_DIR}/${TOP}_${PLATFORM}.xclbin" \
  --kernel ${KERNEL_NAME} \
  --platform ${PLATFORM} \
  --target ${TARGET} \
  --report_level 2 \
  --temp_dir "${OUTPUT_DIR}/${TOP}_${PLATFORM}.temp" \
  --optimize 3 \
  --connectivity.nk ${KERNEL_NAME}:1:${KERNEL_NAME} \
  --save-temps \
  ${XO} \
  --config ${CONFIG_FILE} \
  --kernel_frequency ${TARGET_FREQUENCY} \
  --vivado.prop run.impl_1.STEPS.PHYS_OPT_DESIGN.is_enabled=1 \
  --vivado.prop run.impl_1.STEPS.OPT_DESIGN.ARGS.DIRECTIVE=Explore \
  --vivado.prop run.impl_1.STEPS.PLACE_DESIGN.ARGS.DIRECTIVE=EarlyBlockPlacement \
  --vivado.prop run.impl_1.STEPS.PHYS_OPT_DESIGN.ARGS.DIRECTIVE=Explore \
  --vivado.prop run.impl_1.STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE=Explore \
  --vivado.prop run.impl_1.STEPS.OPT_DESIGN.TCL.PRE=$CONSTRAINT
