# TCL Script for LeNet HLS Synthesis
# Generated by HLSFactory

# Create project
open_project LeNet

# Set top function
set_top network

# Add source files
add_files src.cpp
add_files -tb tb.cpp

# Add include paths
add_files -cflags "-I./includes"
add_files -tb -cflags "-I./includes"

# Open solution
open_solution "solution1"

# Set target part (can be changed based on target device)
set_part {xcvu9p-flga2104-2-i}

# Create clock with 10ns period (100MHz)
create_clock -period 10 -name default

# HLS Configuration
config_compile -pipeline_loops 1
config_export -format ip_catalog -rtl vhdl

# Run C simulation (optional - requires testbench data)
# csynth_design
# cosim_design

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog -description "LeNet Spiking CNN" -vendor "SFU-HiAccel" -version "1.0"

# Close project
close_project
