def build_prompt(repo_name: str) -> str:
    return (
        f"Process the HLS repository at './{repo_name}' and extract all HLS designs into the directory "
        f"'output_hls_designs/{repo_name}' in the current working directory.\n"
        "\n"
        "## Pipeline Steps\n"
        "\n"
        "### Step 1: Analyze the Repository\n"
        "Explore the repository to understand its structure and identify ALL HLS designs or potential top-level entry points.\n"
        "Use tools such as `ls`, `tree`, `find`, and `grep` to systematically inspect the codebase.\n"
        "An HLS design is typically:\n"
        "- A C/C++ source file, or set of files, containing a top-level function\n"
        "- Associated with frameworks such as Vitis HLS, Vivado HLS, Intel HLS, Catapult HLS, Dynamatic, or LegUp\n"
        "\n"
        "### Step 2: Extract Each Design\n"
        "For each HLS design or top-level entry point, create a folder:\n"
        f"  output_hls_designs/{repo_name}/<design_name>/\n"
        "\n"
        "Rules:\n"
        f"- Each design must be a direct child of output_hls_designs/{repo_name}/ with no extra nesting\n"
        "- Copy ALL required source files (.cpp, .c, .h)\n"
        "- Copy ALL dependent headers, including shared/common headers from include/, common/, or parent directories\n"
        "- Copy ALL testbench data files required to build or run the design, such as .dat, .txt, .bin, .csv, .hex, .mem, .npy, image files, golden outputs, input vectors, and other runtime assets\n"
        "- Ensure the design folder is fully self-contained\n"
        "- Include a README.md describing the design\n"
        "\n"
        "### Step 3: Convert Non-Vitis HLS Constructs to Vitis HLS Equivalents\n"
        "If a design is implemented using another HLS framework, such as Intel HLS, Catapult HLS, Dynamatic, LegUp, or another C/C++ HLS dialect, "
        "convert the design to use equivalent Vitis HLS constructs whenever possible.\n"
        "Note: A design may already be written for Vitis HLS. In that case, preserve the existing Vitis-compatible code and only perform conversions when the design uses constructs from another HLS framework or non-Vitis HLS dialect.\n"
        "Do not rewrite already-compatible Vitis HLS code unnecessarily.\n"
        "\n"
        "This includes converting:\n"
        "- Arbitrary-precision integer types to Vitis HLS types such as `ap_int<N>` and `ap_uint<N>`\n"
        "- Arbitrary-precision fixed-point types to `ap_fixed<W, I>` or `ap_ufixed<W, I>`\n"
        "- Framework-specific stream/channel/FIFO types to `hls::stream<T>`\n"
        "- Framework-specific memory, interface, or dataflow constructs to equivalent Vitis HLS-compatible C/C++ code\n"
        "- Framework-specific pragmas, attributes, or directives to equivalent `#pragma HLS ...` directives\n"
        "- Framework-specific headers to Vitis-compatible headers such as `ap_int.h`, `ap_fixed.h`, and `hls_stream.h`\n"
        "\n"
        "Examples:\n"
        "- Intel HLS arbitrary-precision integers should be converted to `ap_int` or `ap_uint`\n"
        "- Intel HLS pipes, Catapult channels, or other stream abstractions should be converted to `hls::stream`\n"
        "- Intel, Catapult, Dynamatic, or LegUp pipeline/unroll/interface directives should be translated to equivalent Vitis HLS pragmas\n"
        "\n"
        "The extracted design should be written in a Vitis HLS-compatible form. Do not leave framework-specific constructs unresolved unless there is no reasonable Vitis HLS equivalent.\n"
        "\n"
        "### Step 4: Testbench Handling\n"
        "For each design:\n"
        "- If a testbench exists, copy it and ensure it is self-contained\n"
        "- Ensure all files needed by the testbench at runtime are copied into the design folder so the design can be built and tested standalone\n"
        "- If no testbench exists, generate a complete one that:\n"
        "  - Instantiates and calls the top-level function\n"
        "  - Uses meaningful inputs\n"
        "  - Verifies outputs\n"
        "  - Returns 0 on success and 1 on failure\n"
        "- Do NOT generate placeholder or trivial testbenches\n"
        "\n"
        "### Step 5: Compile Source Files\n"
        "Use the following command for each source file:\n"
        "```\n"
        "clang++ -std=c++17 -I/workspace/vitis_hls_include -I<design_dir> -w -fsyntax-only <file.cpp>\n"
        "```\n"
        "Notes:\n"
        "- `-w` suppresses warnings\n"
        "- `-fsyntax-only` checks syntax only\n"
        "- If compilation fails due to missing headers, locate and copy dependencies, then retry\n"
        "- Record results in compile_log.txt in each design folder\n"
        "\n"
        "### Step 6: Compile and Run Testbench\n"
        "- Compile the testbench\n"
        "- Execute it with a timeout (default 30 seconds)\n"
        "- Example run command: `timeout 30s ./testbench.out`\n"
        "- Do NOT run testbench binaries without a timeout\n"
        "- If timeout occurs, treat it as a failure (possible deadlock / infinite loop) and debug/fix before continuing\n"
        "- If it fails, you MUST attempt to fix the issue\n"
        "\n"
        "### Step 7: Generate TCL Script\n"
        "Create synth.tcl for each design with:\n"
        "- `set_top` matching the actual top-level function\n"
        "- `set_part` from the repo if specified, otherwise use `xczu9eg-ffvb1156-2-i`\n"
        "- `add_files` for sources\n"
        "- `add_files -tb` for testbench\n"
        "- `open_solution`, `csynth_design`, and `exit`\n"
        "\n"
        "### Step 8: Final Organization\n"
        "Ensure all designs are located under:\n"
        f"  output_hls_designs/{repo_name}/\n"
        "Verify with:\n"
        "```\n"
        "find output_hls_designs -type f | head -50\n"
        "```\n"
        "\n"
        "## Important Rules\n"
        "- Process ALL valid designs. Do not skip any.\n"
        "- Start executing immediately. Do not only describe steps.\n"
        "- The final extracted designs should be compatible with Vitis HLS whenever possible.\n"
        "\n"
        "## Pre-Ending Checklist (MANDATORY)\n"
        "Before finishing, verify:\n"
        f"1. Run `ls output_hls_designs/{repo_name}/ | wc -l` and call this N\n"
        "2. Each detected design corresponds to exactly ONE folder\n"
        "3. No aggregated or single-folder outputs are allowed\n"
        "4. Each design folder contains:\n"
        "   - At least one source file (.cpp or .c)\n"
        "   - testbench.cpp\n"
        "   - synth.tcl\n"
        "5. Any testbench data files required at runtime are present inside the corresponding design folder\n"
        "Do NOT terminate until all checks pass.\n"
        "\n"
        "## Error Handling\n"
        "If compilation or testbench execution fails:\n"
        "Repeat up to 3 times:\n"
        "1. Analyze error messages\n"
        "2. Fix the issue\n"
        "3. Recompile and re-run\n"
        "\n"
        "## Special Cases\n"
        "- Skip designs using TAPA (`#include <tapa.h>`, `tapa::mmap`, `tapa::stream`, etc.)\n"
        "- Do not skip non-Vitis HLS designs only because they use another HLS framework. Instead, attempt to convert them to Vitis HLS-compatible code.\n"
        "\n"
        "## Notes on Design Extraction\n"
        "- Some repositories contain multiple kernels sharing utilities. Extract each as a separate design and duplicate dependencies\n"
        "- Some top-level programs are not HLS but contain HLS subcomponents. Extract subcomponents individually\n"
        "- Some designs are parameterized variants. Treat each variant as a separate design\n"
        "\n"
        "Use best effort when boundaries are unclear. Prefer over-extraction rather than missing designs.\n"
    )


def build_prompt_v2(repo_name: str) -> str:
    base_prompt = build_prompt(repo_name)
    return base_prompt + (
        "\n"
        "## Common Issues to Avoid\n"
        "Use these guardrails while extracting each design.\n"
        "\n"
        "### 1) Avoid TCL Script Ordering Errors\n"
        "- In `synth.tcl`, call commands in this order: `open_project`, `set_top`, `add_files`, `add_files -tb`, `open_solution`, `set_part`, `create_clock` (if used), `csynth_design`, `exit`\n"
        "- Never call `set_part` before `open_solution`\n"
        "\n"
        "### 2) Avoid TCL `add_files` API Misuse\n"
        "- Do not pass many source files to a single `add_files` call as positional arguments\n"
        "- Add each file with a separate `add_files <file>` line\n"
        "- Use `add_files -tb <testbench_file>` for testbench files\n"
        "- Do not repeat `-tb` options in one command\n"
        "\n"
        "### 3) Avoid Missing Headers / Source Dependencies\n"
        "- Before finalizing a design folder, resolve and copy every transitive include dependency used by all source/testbench files\n"
        "- Include shared headers from `include/`, `common/`, and parent utility directories when referenced\n"
        "- If compile reports `file not found`, copy the missing file and retry until clean\n"
        "\n"
        "### 4) Avoid C/C++ Compile Failures in Extracted Designs\n"
        "- Ensure required typedefs, constants, declarations, and helper symbols are copied with the design\n"
        "- Ensure converted code uses valid Vitis types and includes (`ap_int.h`, `ap_fixed.h`, `hls_stream.h`) when needed\n"
        "- If symbols are undefined, trace back to their defining file and copy it\n"
        "\n"
        "### 5) Avoid Unsupported HLS Constructs\n"
        "- Eliminate recursion from top-level kernels and called compute functions\n"
        "- Avoid illegal scalar-port address computations; rewrite using arrays, local buffers, or legal indexing structures\n"
        "\n"
        "### 6) Avoid Pragma Conflicts\n"
        "- Do not apply conflicting `UNROLL` and `PIPELINE` directives to the same loop scope in incompatible ways\n"
        "- If a loop is pipelined, avoid complete unroll directives that violate scheduling constraints\n"
        "\n"
        "### 7) Avoid Part / Tool Option Failures\n"
        "- Use plain `set_part <part_name>` only; do not use unsupported options (for example `-tool`)\n"
        "- If repo-specified part is unavailable, fallback to `xczu9eg-ffvb1156-2-i` and document fallback in README\n"
        "\n"
        "### 8) Avoid Timeout-Driven Failures\n"
        "- Keep pragmas and transformations conservative enough for csynth to complete\n"
        "- Prefer correctness and completion over aggressive pragma combinations that cause long or unstable synthesis\n"
        "- Always run testbench binaries with a timeout (default 30 seconds), for example `timeout 30s ./testbench.out`\n"
        "- If a testbench times out, treat it as deadlock/spin behavior and fix root cause before proceeding\n"
        "\n"
        "### 9) Avoid Silent Unknown Failures\n"
        "- On any non-zero tool return, inspect full tool output/log and fix root cause before proceeding\n"
        "- Do not treat unknown non-zero returns as acceptable; retry after concrete fixes\n"
        "\n"
    )