# TCL Synthesis Script for orc_proc
# Auto-generated by HLSFactory

# Create project
open_project orc_proc_proj

# Set top function
set_top orc_proc

# Add source files
add_files src/orc_proc.cpp
add_files -tb src/orc_proc.h
add_files -tb src/orcDecomp.h
add_files -tb src/orc_filter.h
add_files -tb src/orc_decoder.h
add_files -tb src/zlibTapa.h
add_files -tb src/fixed_codes.hpp

# Add testbench
add_files -tb tb/orc_proc_tb.cpp

# Open solution
open_solution "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock
create_clock -period 3.333 -name default

# Set TAPA-specific configurations
config_interface -m_axi_addr64=true

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog -description "FORC: FPGA-based ORC Filter - Accelerates Apache ORC file decompression and filtering on FPGA using TAPA framework" -vendor "SFU-HiAccel" -version "1.0"

# Exit
exit
