# Vitis HLS Synthesis Script for k_gaussian_quadrature_a
# Auto-generated by HLSFactory

open_project k_gaussian_quadrature_a_proj
set_top k_gaussian_quadrature_a

# Add source files
add_files k_gaussian_quadrature_a.cpp

# Add testbench
add_files -tb tb_k_gaussian_quadrature_a.cpp

# Open solution
open_solution -reset "solution1"

# Set target device (Alveo U280)
set_part {xcu280-fsvh2892-2L-e}

# Create clock (300MHz default)
create_clock -period 3.33 -name default

# Run C synthesis
csynth_design

# Export design (optional)
# export_design -rtl verilog -format ip_catalog

exit
