# TCL Synthesis Script for NiN
# Generated by HLSFactory Pipeline

# Open project
open_project nin

# Add source files
add_files src/src.cpp -cflags "-Iinclude"
add_files -tb tb/tb.cpp -cflags "-Iinclude"

# Set top function
set_top network

# Open solution
open_solution "solution1"

# Set target device (Xilinx ZCU104)
set_part {xczu7ev-ffvc1156-2-e}

# Create clock
create_clock -period 10 -name default

# Configure HLS
config_compile -pipeline_loops 64
config_interface -m_axi_addr64

# Run synthesis
csynth_design

# Export RTL
export_design -format ip_catalog -display_name "NiN_Spiking_NN"

exit
