# TCL Synthesis Script for reg_stencil-dilate_tapa
# Auto-generated by HLSFactory

# Open/create project
open_project reg_stencil-dilate_tapa
set_top DILATE

# Add source files
add_files unikernel.cpp
add_files DILATE.h
add_files -tb testbench.cpp

# Open solution
open_solution -reset "solution1"

# Set target device
set_part {xcu280-fsvh2892-2L-e}

# Create clock with 10ns period
create_clock -period 10 -name default

# Run C simulation
csim_design

# Run C synthesis
csynth_design

# Run C/RTL cosimulation (optional)
# cosim_design

# Export design (optional)
# export_design -format ip_catalog

exit
