# TCL Synthesis Script for TDLCA_CBIR
# Generated by HLSFactory

open_project -reset TDLCA_CBIR_proj

# Add source files
add_files TDLCA_CBIR.cpp
add_files -tb ManhattanDistLCacc.h
add_files -tb MatMul400LCacc.h
add_files -tb MatMulLCacc.h
add_files -tb PartialSortLCacc.h
add_files -tb PoolLCacc.h
add_files -tb ReluLCacc.h

# Set top function
set_top CBIRLCacc

# Create solution
open_solution -reset "solution1"

# Set target device (Xilinx Virtex-7)
set_part {xc7vx485tffg1761-2}

# Create clock with 10ns period (100MHz)
create_clock -period 10

# Run synthesis
csynth_design

# Export design
export_design -format ip_catalog

exit
